version: '3'

services:
    
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./excelplay-client/dist/excelplay/:/usr/share/nginx/html/
            - ./static:/var/www/static/
            - ./media:/var/www/media/
        depends_on:
            - auth1
            - kryptos
            - dalalbull
            - dalalbulldaphne
    
    auth1:
        build: ./excelplay-auth/excelplay_auth/.
        depends_on:
            - redis
            - db
        command: bash excelplay-auth/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_auth
        ports:
            - "8000:8000"
        environment:
            - secret_key=$secret_key
        
    kryptos:
        build: ./excelplay-kryptos/excelplay_kryptos/.
        depends_on:
            - redis
            - db2
        command: bash excelplay-kryptos/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_kryptos
            - 'staticdata:/excelplay/excelplay_kryptos/excelplay-kryptos/excelplay_kryptos/static'
        ports:
            - "8001:8001"
            
        environment:
            - secret_key=$secret_key

    dalalbull:
        build: ./excelplay-dalalbull/excelplay_dalalbull/.
        depends_on:
            - redis
            - db3
   
        command: bash excelplay-dalalbull/docker_entrypoint.sh

        volumes:
            - .:/excelplay/excelplay_dalalbull
        ports:
            - "8002:8002"
    
    echo:
        build: ./excelplay-echo/excelplay_echo/.
        depends_on:
            - db4
        command: python /excelplay-echo/excelplay_echo/excelplay_echo/manage.py migrate --noinput
        command: python /excelplay-echo/excelplay_echo/excelplay_echo/manage.py runserver
        volumes:
            - .:/excelplay/excelplay_echo/
        ports:
            - "8010:8010"
         
    worker:
        build: ./excelplay-dalalbull/excelplay_dalalbull/.
        command: python excelplay-dalalbull/excelplay_dalalbull/manage.py runworker LeaderBoard Portfolio nifty_channel graph_data_channel ticker_data_channel sell_channel && 

    dalalbulldaphne:
        build: ./excelplay-dalalbull/excelplay_dalalbull/.
        depends_on:
            - dalalbull

        command: bash excelplay-dalalbull/rundaphne.sh
        volumes:
            - .:/excelplay/excelplay_dalalbull
        ports:
            - "8003:8003"

    dalalbullcelery:
        build: ./excelplay-dalalbull/excelplay_dalalbull/.
        depends_on:
            - dalalbull
            - dalalbulldaphne

        command: bash excelplay-dalalbull/runcelery.sh
        volumes:
            - .:/excelplay/excelplay_dalalbull

    db:
        container_name: 'db'
        restart: always
        image: postgres:alpine
        expose:
            - '5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data'

    db2:
        container_name: 'db2'
        restart: always
        image: postgres:alpine
        expose:
            - "5433"
        ports:
            - "5433:5432"
        volumes:
            - 'pgdata2:/var/lib/postgresql/data'
 
    db3:
        container_name: 'db3'
        restart: always
        image: postgres:alpine
        expose:
            - "5434"
        ports:
            - "5434:5432"
        volumes:
            - 'pgdata3:/var/lib/postgresql/data'

    db4:
        container_name: 'db4'
        restart: always
        image: postgres:alpine
        expose:
            - "5435"
        ports:
            - "5435:5435"
        volumes:
            - 'pgdata4:/var/lib/postgresql/data'
            
    redis:
        container_name: 'redis'
        restart: always
        image: redis
        command: redis-server
        volumes:
            - 'redisdata:/data'

 #   redis2:
 #       container_name: 'redis2'
 #       restart: always
 #       image: redis
 #       command: redis-server --port 6378
 #       volumes:
 #           - 'redisdata2:/data'



volumes:
    pgdata2:
    pgdata:
    pgdata3:
    redisdata:
    staticdata:
    pgdata4:
#    redisdata2:

